/*
This module will generate config for our ansible playbooks
We need to pass env, region and cluster name for all applications to
our ansible roles.
Two provisioners to be used
- create time ( deploy all services )
- destroy time ( delete all ecs cluster else tf wont be able to destroy completely )
*/


data "template_file" "ansible_ecs_deploy" {
     template   = "${file("${path.module}/templates/ansible_ecs_deploy.sh")}"

     vars {
       env                          = "${lower(var.env)}"
       region                       = "${var.region}"
       log_group_name               = "${var.log_group_name}"
       repository_credentials_arn   = "${var.repository_credentials_arn}"
       ecs_role_arn                 = "${var.ecs_role_arn}"
       kafka_sg_id                  = "${var.kafka_sg_id}"
       private_subnet_0             = "${var.private_subnet_ids[0]}"
       private_subnet_1             = "${var.private_subnet_ids[1]}"
       private_subnet_2             = "${var.private_subnet_ids[2]}"
       kafka_internal_elb_dns       = "${var.kafka_internal_elb_dns}"
       site_external_elb_dns        = "${var.site_external_elb_dns}"
       anomaly_info_url             = "${var.anomaly_info_url}"
       api_username                 = "${var.api_username}"
       api_password                 = "${var.api_password}"
       mongo_db_name                  = "${var.mongo_db_name}"
       mongo_fqdn                     = "${var.mongo_fqdn}"
       ehs_mongo_alerts_mongo_username     = "${var.ehs_mongo_alerts_mongo_username}"
       event_history_service_mongo_username = "${var.event_history_service_mongo_username}"
       ehs_mongo_events_mongo_username     = "${var.ehs_mongo_events_mongo_username}"
       ehs_mongo_alerts_mongo_pw      = "${var.ehs_mongo_alerts_mongo_pw}"
       event_history_service_mongo_pw = "${var.event_history_service_mongo_pw}"
       ehs_mongo_events_mongo_pw      = "${var.ehs_mongo_events_mongo_pw}"
       asset_manager_mongo_pw        = "${var.asset_manager_mongo_pw}"
       escalation_manager_mongo_pw   = "${var.escalation_manager_mongo_pw}"
       notification_permissions_manager_mongo_pw = "${var.notification_permissions_manager_mongo_pw}"
       offline_sensor_manager_mongo_pw = "${var.offline_sensor_manager_mongo_pw}"
       permissions_manager_mongo_pw  = "${var.permissions_manager_mongo_pw}"
       sensor_manager_mongo_pw       = "${var.sensor_manager_mongo_pw}"
       site_manager_mongo_pw         = "${var.site_manager_mongo_pw}"
       system_manager_mongo_pw       = "${var.system_manager_mongo_pw}"
       threshold_model_manager_mongo_pw = "${var.threshold_model_manager_mongo_pw}"
       roc_model_manager_mongo_pw    = "${var.roc_model_manager_mongo_pw}"
       spike_model_manager_mongo_pw  = "${var.spike_model_manager_mongo_pw}"
       user_manager_mongo_pw         = "${var.user_manager_mongo_pw}"
       CHANGELOG_REPLICATION_FACTOR = "${var.CHANGELOG_REPLICATION_FACTOR}"
       jwt_key                       = "${var.jwt_key}"
       external_app_url              = "${var.external_app_url}"
       new_user_email                = "${var.new_user_email}"
       notify_requests_email         = "${var.notify_requests_email}"
       default_to                    = "${var.default_to}"
       twilio_call_back_url          = "${var.twilio_call_back_url}"
       twilio_status_call_back_url   = "${var.twilio_status_call_back_url}"

       port_8080                             = "${var.port_8080}"
       kafka_port                            = "${var.kafka_port}"
       zookeeper_port                        = "${var.zookeeper_port}"
       anomaly_processor_port                = "${var.anomaly_processor_port}"
       asset_enricher_port                   = "${var.asset_enricher_port}"
       asset_manager_port                    = "${var.asset_manager_port}"
       control_center_port                   = "${var.control_center_port}"
       email_notification_service_port       = "${var.email_notification_service_port}"
       escalation_manager_port               = "${var.escalation_manager_port}"
       escalation_service_port               = "${var.escalation_service_port}"
       mute_manager_port                     = "${var.mute_manager_port}"
       notification_permissions_manager_port = "${var.notification_permissions_manager_port}"
       notifications_enricher_port           = "${var.notifications_enricher_port}"
       offline_sensor_manager_port           = "${var.offline_sensor_manager_port}"
       offline_sensor_monitor_port           = "${var.offline_sensor_monitor_port}"
       permissions_manager_port              = "${var.permissions_manager_port}"
       response_manager_port                 = "${var.response_manager_port}"
       sensor_manager_port                   = "${var.sensor_manager_port}"
       site_enricher_port                    = "${var.site_enricher_port}"
       site_manager_port                     = "${var.site_manager_port}"
       system_manager_port                   = "${var.system_manager_port}"
       telegram_inbound_service_port         = "${var.telegram_inbound_service_port}"
       telegram_notification_service_port    = "${var.telegram_notification_service_port}"
       threshold_anomaly_detector_port       = "${var.threshold_anomaly_detector_port}"
       threshold_model_manager_port          = "${var.threshold_model_manager_port}"
       rateofchange_model_manager_port       = "${var.rateofchange_model_manager_port}"
       rateofchange_anomaly_detector_port    = "${var.rateofchange_anomaly_detector_port}"
       spike_model_manager_port              = "${var.spike_model_manager_port}"
       api_gateway_port                      = "${var.api_gateway_port}"
       ttn_dc2_raw_port                      = "${var.ttn_dc2_raw_port}"
       ttn_transformer_port                  = "${var.ttn_transformer_port}"
       user_enricher_port                    = "${var.user_enricher_port}"
       user_manager_port                     = "${var.user_manager_port}"
       mute_service_port                     = "${var.mute_service_port}"
       mute_service_port                     = "${var.mute_service_port}"
       ehs_port                              = "${var.ehs_port}"
       north_data_source_port                = "${var.north_data_source_port}"
       loxone_data_source_port               = "${var.loxone_data_source_port}"
       generic_data_source_port              = "${var.generic_data_source_port}"
       sigfox_data_source_port               = "${var.sigfox_data_source_port}"
       texecom_data_source_port              = "${var.texecom_data_source_port}"
       webway_data_source_port               = "${var.webway_data_source_port}"

       api_gateway_target_group_arn                      = "${var.api_gateway_target_group_arn}"
       anomaly_processor_target_group_arn                = "${var.anomaly_processor_target_group_arn}"
       asset_enricher_target_group_arn                   = "${var.asset_enricher_target_group_arn}"
       asset_manager_target_group_arn                    = "${var.asset_manager_target_group_arn}"
       control_center_target_group_arn                   = "${var.control_center_target_group_arn}"
       email_notification_service_target_group_arn       = "${var.email_notification_service_target_group_arn}"
       escalation_manager_target_group_arn               = "${var.escalation_manager_target_group_arn}"
       escalation_service_target_group_arn               = "${var.escalation_service_target_group_arn}"
       mute_manager_target_group_arn                     = "${var.mute_manager_target_group_arn}"
       notification_permissions_manager_target_group_arn = "${var.notification_permissions_manager_target_group_arn}"
       notifications_enricher_target_group_arn           = "${var.notifications_enricher_target_group_arn}"
       offline_sensor_manager_target_group_arn           = "${var.offline_sensor_manager_target_group_arn}"
       offline_sensor_monitor_target_group_arn           = "${var.offline_sensor_monitor_target_group_arn}"
       permissions_manager_target_group_arn              = "${var.permissions_manager_target_group_arn}"
       response_manager_target_group_arn                 = "${var.response_manager_target_group_arn}"
       sensor_manager_target_group_arn                   = "${var.sensor_manager_target_group_arn}"
       site_enricher_target_group_arn                    = "${var.site_enricher_target_group_arn}"
       site_manager_target_group_arn                     = "${var.site_manager_target_group_arn}"
       system_manager_target_group_arn                   = "${var.system_manager_target_group_arn}"
       telegram_inbound_service_target_group_arn         = "${var.telegram_inbound_service_target_group_arn}"
       telegram_notification_service_target_group_arn    = "${var.telegram_notification_service_target_group_arn}"
       threshold_anomaly_detector_target_group_arn       = "${var.threshold_anomaly_detector_target_group_arn}"
       threshold_model_manager_target_group_arn          = "${var.threshold_model_manager_target_group_arn}"
       rateofchange_model_manager_target_group_arn       = "${var.rateofchange_model_manager_target_group_arn}"
       rateofchange_anomaly_detector_target_group_arn    = "${var.rateofchange_anomaly_detector_target_group_arn}"
       spike_model_manager_target_group_arn              = "${var.spike_model_manager_target_group_arn}"
       ttn_dc2_raw_target_group_arn                      = "${var.ttn_dc2_raw_target_group_arn}"
       ttn_transformer_target_group_arn                  = "${var.ttn_transformer_target_group_arn}"
       user_enricher_target_group_arn                    = "${var.user_enricher_target_group_arn}"
       user_manager_target_group_arn                     = "${var.user_manager_target_group_arn}"
       mute_service_target_group_arn                     = "${var.mute_service_target_group_arn}"
       loxone_data_source_target_group_arn               = "${var.loxone_data_source_target_group_arn}"
       generic_data_source_target_group_arn              = "${var.generic_data_source_target_group_arn}"
       sigfox_data_source_target_group_arn               = "${var.sigfox_data_source_target_group_arn}"
       webway_data_source_target_group_arn               = "${var.webway_data_source_target_group_arn}"
       ehs_target_group_arn                              = "${var.ehs_target_group_arn}"
       gwt_data_source_target_group_arn                  = "${var.gwt_data_source_target_group_arn}"
     }

}

data "template_file" "ansible_ecs_destroy" {
     template   = "${file("${path.module}/templates/ansible_ecs_destroy.sh")}"

     vars {
       env                          = "${lower(var.env)}"
       region                       = "${var.region}"
       log_group_name               = "${var.log_group_name}"
       repository_credentials_arn   = "${var.repository_credentials_arn}"
       ecs_role_arn                 = "${var.ecs_role_arn}"
       ecs_role_arn                 = "${var.ecs_role_arn}"
       kafka_sg_id                  = "${var.kafka_sg_id}"
       private_subnet_0             = "${var.private_subnet_ids[0]}"
       private_subnet_1             = "${var.private_subnet_ids[1]}"
       private_subnet_2             = "${var.private_subnet_ids[2]}"
       kafka_internal_elb_dns       = "${var.kafka_internal_elb_dns}"
       site_external_elb_dns        = "${var.site_external_elb_dns}"
       anomaly_info_url             = "${var.anomaly_info_url}"
       api_username                 = "${var.api_username}"
       api_password                 = "${var.api_password}"
       mongo_db_name                  = "${var.mongo_db_name}"
       mongo_fqdn                     = "${var.mongo_fqdn}"
       ehs_mongo_alerts_mongo_username     = "${var.ehs_mongo_alerts_mongo_username}"
       event_history_service_mongo_username = "${var.event_history_service_mongo_username}"
       ehs_mongo_events_mongo_username     = "${var.ehs_mongo_events_mongo_username}"
       ehs_mongo_alerts_mongo_pw      = "${var.ehs_mongo_alerts_mongo_pw}"
       event_history_service_mongo_pw = "${var.event_history_service_mongo_pw}"
       asset_manager_mongo_pw        = "${var.asset_manager_mongo_pw}"
       escalation_manager_mongo_pw   = "${var.escalation_manager_mongo_pw}"
       notification_permissions_manager_mongo_pw = "${var.notification_permissions_manager_mongo_pw}"
       offline_sensor_manager_mongo_pw = "${var.offline_sensor_manager_mongo_pw}"
       permissions_manager_mongo_pw  = "${var.permissions_manager_mongo_pw}"
       sensor_manager_mongo_pw       = "${var.sensor_manager_mongo_pw}"
       site_manager_mongo_pw         = "${var.site_manager_mongo_pw}"
       system_manager_mongo_pw       = "${var.system_manager_mongo_pw}"
       threshold_model_manager_mongo_pw = "${var.threshold_model_manager_mongo_pw}"
       roc_model_manager_mongo_pw    = "${var.roc_model_manager_mongo_pw}"
       spike_model_manager_mongo_pw  = "${var.spike_model_manager_mongo_pw}"
       user_manager_mongo_pw         = "${var.user_manager_mongo_pw}"
       ehs_mongo_events_mongo_pw      = "${var.ehs_mongo_events_mongo_pw}"
       CHANGELOG_REPLICATION_FACTOR = "${var.CHANGELOG_REPLICATION_FACTOR}"
       jwt_key                       = "${var.jwt_key}"
       external_app_url              = "${var.external_app_url}"
       new_user_email                = "${var.new_user_email}"
       notify_requests_email         = "${var.notify_requests_email}"
       default_to                    = "${var.default_to}"
       twilio_call_back_url          = "${var.twilio_call_back_url}"
       twilio_status_call_back_url   = "${var.twilio_status_call_back_url}"

       port_8080                             = "${var.port_8080}"
       kafka_port                            = "${var.kafka_port}"
       zookeeper_port                        = "${var.zookeeper_port}"
       anomaly_processor_port                = "${var.anomaly_processor_port}"
       asset_enricher_port                   = "${var.asset_enricher_port}"
       asset_manager_port                    = "${var.asset_manager_port}"
       control_center_port                   = "${var.control_center_port}"
       email_notification_service_port       = "${var.email_notification_service_port}"
       escalation_manager_port               = "${var.escalation_manager_port}"
       escalation_service_port               = "${var.escalation_service_port}"
       mute_manager_port                     = "${var.mute_manager_port}"
       notification_permissions_manager_port = "${var.notification_permissions_manager_port}"
       notifications_enricher_port           = "${var.notifications_enricher_port}"
       offline_sensor_manager_port           = "${var.offline_sensor_manager_port}"
       offline_sensor_monitor_port           = "${var.offline_sensor_monitor_port}"
       permissions_manager_port              = "${var.permissions_manager_port}"
       response_manager_port                 = "${var.response_manager_port}"
       sensor_manager_port                   = "${var.sensor_manager_port}"
       site_enricher_port                    = "${var.site_enricher_port}"
       site_manager_port                     = "${var.site_manager_port}"
       system_manager_port                   = "${var.system_manager_port}"
       telegram_inbound_service_port         = "${var.telegram_inbound_service_port}"
       telegram_notification_service_port    = "${var.telegram_notification_service_port}"
       threshold_anomaly_detector_port       = "${var.threshold_anomaly_detector_port}"
       threshold_model_manager_port          = "${var.threshold_model_manager_port}"
       rateofchange_model_manager_port       = "${var.rateofchange_model_manager_port}"
       rateofchange_anomaly_detector_port    = "${var.rateofchange_anomaly_detector_port}"
       spike_model_manager_port              = "${var.spike_model_manager_port}"
       api_gateway_port                      = "${var.api_gateway_port}"
       ttn_dc2_raw_port                      = "${var.ttn_dc2_raw_port}"
       ttn_transformer_port                  = "${var.ttn_transformer_port}"
       user_enricher_port                    = "${var.user_enricher_port}"
       user_manager_port                     = "${var.user_manager_port}"
       mute_service_port                     = "${var.mute_service_port}"
       ehs_port                              = "${var.ehs_port}"
       north_data_source_port                = "${var.north_data_source_port}"
       loxone_data_source_port               = "${var.loxone_data_source_port}"
       generic_data_source_port              = "${var.generic_data_source_port}"
       sigfox_data_source_port               = "${var.sigfox_data_source_port}"
       texecom_data_source_port              = "${var.texecom_data_source_port}"
       webway_data_source_port               = "${var.webway_data_source_port}"

       api_gateway_target_group_arn                      = "${var.api_gateway_target_group_arn}"
       anomaly_processor_target_group_arn                = "${var.anomaly_processor_target_group_arn}"
       asset_enricher_target_group_arn                   = "${var.asset_enricher_target_group_arn}"
       asset_manager_target_group_arn                    = "${var.asset_manager_target_group_arn}"
       control_center_target_group_arn                   = "${var.control_center_target_group_arn}"
       email_notification_service_target_group_arn       = "${var.email_notification_service_target_group_arn}"
       escalation_manager_target_group_arn               = "${var.escalation_manager_target_group_arn}"
       escalation_service_target_group_arn               = "${var.escalation_service_target_group_arn}"
       mute_manager_target_group_arn                     = "${var.mute_manager_target_group_arn}"
       notification_permissions_manager_target_group_arn = "${var.notification_permissions_manager_target_group_arn}"
       notifications_enricher_target_group_arn           = "${var.notifications_enricher_target_group_arn}"
       offline_sensor_manager_target_group_arn           = "${var.offline_sensor_manager_target_group_arn}"
       offline_sensor_monitor_target_group_arn           = "${var.offline_sensor_monitor_target_group_arn}"
       permissions_manager_target_group_arn              = "${var.permissions_manager_target_group_arn}"
       response_manager_target_group_arn                 = "${var.response_manager_target_group_arn}"
       sensor_manager_target_group_arn                   = "${var.sensor_manager_target_group_arn}"
       site_enricher_target_group_arn                    = "${var.site_enricher_target_group_arn}"
       site_manager_target_group_arn                     = "${var.site_manager_target_group_arn}"
       system_manager_target_group_arn                   = "${var.system_manager_target_group_arn}"
       telegram_inbound_service_target_group_arn         = "${var.telegram_inbound_service_target_group_arn}"
       telegram_notification_service_target_group_arn    = "${var.telegram_notification_service_target_group_arn}"
       threshold_anomaly_detector_target_group_arn       = "${var.threshold_anomaly_detector_target_group_arn}"
       threshold_model_manager_target_group_arn          = "${var.threshold_model_manager_target_group_arn}"
       rateofchange_model_manager_target_group_arn       = "${var.rateofchange_model_manager_target_group_arn}"
       rateofchange_anomaly_detector_target_group_arn    = "${var.rateofchange_anomaly_detector_target_group_arn}"
       spike_model_manager_target_group_arn              = "${var.spike_model_manager_target_group_arn}"
       ttn_dc2_raw_target_group_arn                      = "${var.ttn_dc2_raw_target_group_arn}"
       ttn_transformer_target_group_arn                  = "${var.ttn_transformer_target_group_arn}"
       user_enricher_target_group_arn                    = "${var.user_enricher_target_group_arn}"
       user_manager_target_group_arn                     = "${var.user_manager_target_group_arn}"
       mute_service_target_group_arn                     = "${var.mute_service_target_group_arn}"
       loxone_data_source_target_group_arn               = "${var.loxone_data_source_target_group_arn}"
       generic_data_source_target_group_arn              = "${var.generic_data_source_target_group_arn}"
       sigfox_data_source_target_group_arn               = "${var.sigfox_data_source_target_group_arn}"
       webway_data_source_target_group_arn               = "${var.webway_data_source_target_group_arn}"
       ehs_target_group_arn                              = "${var.ehs_target_group_arn}"
       gwt_data_source_target_group_arn                  = "${var.gwt_data_source_target_group_arn}"
     }

}

data "template_file" "ansible_ecs_update" {
  template   = "${file("${path.module}/templates/ansible_ecs_update.sh")}"

  vars {
    env                          = "${lower(var.env)}"
    region                       = "${var.region}"
    log_group_name               = "${var.log_group_name}"
    repository_credentials_arn   = "${var.repository_credentials_arn}"
    ecs_role_arn                 = "${var.ecs_role_arn}"
    kafka_sg_id                  = "${var.kafka_sg_id}"
    private_subnet_0             = "${var.private_subnet_ids[0]}"
    private_subnet_1             = "${var.private_subnet_ids[1]}"
    private_subnet_2             = "${var.private_subnet_ids[2]}"
    kafka_internal_elb_dns       = "${var.kafka_internal_elb_dns}"
    site_external_elb_dns        = "${var.site_external_elb_dns}"
    anomaly_info_url             = "${var.anomaly_info_url}"
    api_username                 = "${var.api_username}"
    api_password                 = "${var.api_password}"
    mongo_db_name                  = "${var.mongo_db_name}"
    mongo_fqdn                     = "${var.mongo_fqdn}"
    ehs_mongo_alerts_mongo_username     = "${var.ehs_mongo_alerts_mongo_username}"
    event_history_service_mongo_username = "${var.event_history_service_mongo_username}"
    ehs_mongo_events_mongo_username     = "${var.ehs_mongo_events_mongo_username}"
    ehs_mongo_alerts_mongo_username     = "${var.ehs_mongo_alerts_mongo_username}"
    event_history_service_mongo_username = "${var.event_history_service_mongo_username}"
    ehs_mongo_events_mongo_username     = "${var.ehs_mongo_events_mongo_username}"
    ehs_mongo_alerts_mongo_pw      = "${var.ehs_mongo_alerts_mongo_pw}"
    event_history_service_mongo_pw = "${var.event_history_service_mongo_pw}"
    ehs_mongo_events_mongo_pw      = "${var.ehs_mongo_events_mongo_pw}"
    asset_manager_mongo_pw        = "${var.asset_manager_mongo_pw}"
    escalation_manager_mongo_pw   = "${var.escalation_manager_mongo_pw}"
    notification_permissions_manager_mongo_pw = "${var.notification_permissions_manager_mongo_pw}"
    offline_sensor_manager_mongo_pw = "${var.offline_sensor_manager_mongo_pw}"
    permissions_manager_mongo_pw  = "${var.permissions_manager_mongo_pw}"
    sensor_manager_mongo_pw       = "${var.sensor_manager_mongo_pw}"
    site_manager_mongo_pw         = "${var.site_manager_mongo_pw}"
    system_manager_mongo_pw       = "${var.system_manager_mongo_pw}"
    threshold_model_manager_mongo_pw = "${var.threshold_model_manager_mongo_pw}"
    roc_model_manager_mongo_pw    = "${var.roc_model_manager_mongo_pw}"
    spike_model_manager_mongo_pw  = "${var.spike_model_manager_mongo_pw}"
    user_manager_mongo_pw         = "${var.user_manager_mongo_pw}"
    CHANGELOG_REPLICATION_FACTOR = "${var.CHANGELOG_REPLICATION_FACTOR}"
    jwt_key                       = "${var.jwt_key}"
    external_app_url              = "${var.external_app_url}"
    new_user_email                = "${var.new_user_email}"
    notify_requests_email         = "${var.notify_requests_email}"
    default_to                    = "${var.default_to}"
    twilio_call_back_url          = "${var.twilio_call_back_url}"
    twilio_status_call_back_url   = "${var.twilio_status_call_back_url}"

    port_8080                             = "${var.port_8080}"
    kafka_port                            = "${var.kafka_port}"
    zookeeper_port                        = "${var.zookeeper_port}"
    anomaly_processor_port                = "${var.anomaly_processor_port}"
    asset_enricher_port                   = "${var.asset_enricher_port}"
    asset_manager_port                    = "${var.asset_manager_port}"
    control_center_port                   = "${var.control_center_port}"
    email_notification_service_port       = "${var.email_notification_service_port}"
    escalation_manager_port               = "${var.escalation_manager_port}"
    escalation_service_port               = "${var.escalation_service_port}"
    mute_manager_port                     = "${var.mute_manager_port}"
    notification_permissions_manager_port = "${var.notification_permissions_manager_port}"
    notifications_enricher_port           = "${var.notifications_enricher_port}"
    offline_sensor_manager_port           = "${var.offline_sensor_manager_port}"
    permissions_manager_port              = "${var.permissions_manager_port}"
    response_manager_port                 = "${var.response_manager_port}"
    sensor_manager_port                   = "${var.sensor_manager_port}"
    site_enricher_port                    = "${var.site_enricher_port}"
    site_manager_port                     = "${var.site_manager_port}"
    system_manager_port                   = "${var.system_manager_port}"
    telegram_inbound_service_port         = "${var.telegram_inbound_service_port}"
    telegram_notification_service_port    = "${var.telegram_notification_service_port}"
    threshold_anomaly_detector_port       = "${var.threshold_anomaly_detector_port}"
    threshold_model_manager_port          = "${var.threshold_model_manager_port}"
    rateofchange_model_manager_port       = "${var.rateofchange_model_manager_port}"
    rateofchange_anomaly_detector_port    = "${var.rateofchange_anomaly_detector_port}"
    spike_model_manager_port              = "${var.spike_model_manager_port}"
    api_gateway_port                      = "${var.api_gateway_port}"
    ttn_dc2_raw_port                      = "${var.ttn_dc2_raw_port}"
    ttn_transformer_port                  = "${var.ttn_transformer_port}"
    user_enricher_port                    = "${var.user_enricher_port}"
    user_manager_port                     = "${var.user_manager_port}"
    mute_service_port                     = "${var.mute_service_port}"
    mute_service_port                     = "${var.mute_service_port}"
    ehs_port                              = "${var.ehs_port}"
    north_data_source_port                = "${var.north_data_source_port}"
    loxone_data_source_port               = "${var.loxone_data_source_port}"
    generic_data_source_port              = "${var.generic_data_source_port}"
    sigfox_data_source_port               = "${var.sigfox_data_source_port}"
    texecom_data_source_port              = "${var.texecom_data_source_port}"
    webway_data_source_port               = "${var.webway_data_source_port}"

    api_gateway_target_group_arn                      = "${var.api_gateway_target_group_arn}"
    anomaly_processor_target_group_arn                = "${var.anomaly_processor_target_group_arn}"
    asset_enricher_target_group_arn                   = "${var.asset_enricher_target_group_arn}"
    asset_manager_target_group_arn                    = "${var.asset_manager_target_group_arn}"
    control_center_target_group_arn                   = "${var.control_center_target_group_arn}"
    email_notification_service_target_group_arn       = "${var.email_notification_service_target_group_arn}"
    escalation_manager_target_group_arn               = "${var.escalation_manager_target_group_arn}"
    escalation_service_target_group_arn               = "${var.escalation_service_target_group_arn}"
    mute_manager_target_group_arn                     = "${var.mute_manager_target_group_arn}"
    notification_permissions_manager_target_group_arn = "${var.notification_permissions_manager_target_group_arn}"
    notifications_enricher_target_group_arn           = "${var.notifications_enricher_target_group_arn}"
    offline_sensor_manager_target_group_arn           = "${var.offline_sensor_manager_target_group_arn}"
    permissions_manager_target_group_arn              = "${var.permissions_manager_target_group_arn}"
    response_manager_target_group_arn                 = "${var.response_manager_target_group_arn}"
    sensor_manager_target_group_arn                   = "${var.sensor_manager_target_group_arn}"
    site_enricher_target_group_arn                    = "${var.site_enricher_target_group_arn}"
    site_manager_target_group_arn                     = "${var.site_manager_target_group_arn}"
    system_manager_target_group_arn                   = "${var.system_manager_target_group_arn}"
    telegram_inbound_service_target_group_arn         = "${var.telegram_inbound_service_target_group_arn}"
    telegram_notification_service_target_group_arn    = "${var.telegram_notification_service_target_group_arn}"
    threshold_anomaly_detector_target_group_arn       = "${var.threshold_anomaly_detector_target_group_arn}"
    threshold_model_manager_target_group_arn          = "${var.threshold_model_manager_target_group_arn}"
    rateofchange_model_manager_target_group_arn       = "${var.rateofchange_model_manager_target_group_arn}"
    rateofchange_anomaly_detector_target_group_arn    = "${var.rateofchange_anomaly_detector_target_group_arn}"
    spike_model_manager_target_group_arn              = "${var.spike_model_manager_target_group_arn}"
    ttn_dc2_raw_target_group_arn                      = "${var.ttn_dc2_raw_target_group_arn}"
    ttn_transformer_target_group_arn                  = "${var.ttn_transformer_target_group_arn}"
    user_enricher_target_group_arn                    = "${var.user_enricher_target_group_arn}"
    user_manager_target_group_arn                     = "${var.user_manager_target_group_arn}"
    mute_service_target_group_arn                     = "${var.mute_service_target_group_arn}"
    loxone_data_source_target_group_arn               = "${var.loxone_data_source_target_group_arn}"
    generic_data_source_target_group_arn              = "${var.generic_data_source_target_group_arn}"
    sigfox_data_source_target_group_arn               = "${var.sigfox_data_source_target_group_arn}"
    webway_data_source_target_group_arn               = "${var.webway_data_source_target_group_arn}"
    ehs_target_group_arn                              = "${var.ehs_target_group_arn}"
    gwt_data_source_target_group_arn                  = "${var.gwt_data_source_target_group_arn}"
  }

}


resource "null_resource" "ansible_ecs_generate" {
   triggers {
      # This will trigger create on every run
      filename = "test-${uuid()}"
   }

   provisioner "local-exec" {
      command = "echo '${ data.template_file.ansible_ecs_deploy.rendered }' > ../../../ansible/ansible_call_deploy.sh"
   }

   provisioner "local-exec" {
      command = "chmod 755 ../../../ansible/ansible_call_deploy.sh"
   }

   provisioner "local-exec" {
      command = "../../../ansible/ansible_call_deploy.sh"
   }

}


/*
resource "null_resource" "ansible_ecs_destroy" {

   triggers {
      template_rendered = "${data.template_file.ansible_ecs_destroy.rendered}"
   }

   provisioner "local-exec" {
      command = "echo '${ data.template_file.ansible_ecs_destroy.rendered }' > ../../../ansible/ansible_call_destroy.sh"
      when    = "destroy"
   }

   provisioner "local-exec" {
      command = "chmod 755 ../../../ansible/ansible_call_destroy.sh"
      when    = "destroy"
   }

   provisioner "local-exec" {
      command = "../../../ansible/ansible_call_destroy.sh"
      when    = "destroy"
   }

}
*/

resource "null_resource" "ansible_ecs_update" {
  depends_on = ["null_resource.ansible_ecs_generate"]

  triggers {
    # This will trigger create on every run
    filename = "test-${uuid()}"
  }

  provisioner "local-exec" {
    command = "echo '${ data.template_file.ansible_ecs_update.rendered }' > ../../../ansible/ansible_call_update.sh"
  }

  provisioner "local-exec" {
    command = "chmod 755 ../../../ansible/ansible_call_update.sh"
  }

  provisioner "local-exec" {
    command = "../../../ansible/ansible_call_update.sh"
  }

}
