variable "env" {}
variable "region" {}
variable "log_group_name" {}
variable "repository_credentials_arn" {}
variable "ecs_role_arn" {}
variable "kafka_sg_id" {}
variable "kafka_internal_elb_dns" {}
variable "site_external_elb_dns" {}
variable "anomaly_info_url" {}
variable "api_username" {}
variable "api_password" {}
variable "mongo_db_name" {}
variable "mongo_fqdn" {}
variable "ehs_mongo_alerts_mongo_username" {}
variable "event_history_service_mongo_username" {}
variable "ehs_mongo_events_mongo_username" {}
variable "ehs_mongo_alerts_mongo_pw" {}
variable "event_history_service_mongo_pw" {}
variable "ehs_mongo_events_mongo_pw" {}
variable "asset_manager_mongo_pw" {}
variable "escalation_manager_mongo_pw" {}
variable "notification_permissions_manager_mongo_pw" {}
variable "offline_sensor_manager_mongo_pw" {}
variable "permissions_manager_mongo_pw" {}
variable "sensor_manager_mongo_pw" {}
variable "site_manager_mongo_pw" {}
variable "system_manager_mongo_pw" {}
variable "threshold_model_manager_mongo_pw" {}
variable "roc_model_manager_mongo_pw" {}
variable "spike_model_manager_mongo_pw" {}
variable "user_manager_mongo_pw" {}
variable "CHANGELOG_REPLICATION_FACTOR" {}
variable "jwt_key" {}
variable "external_app_url" {}
variable "new_user_email" {}
variable "notify_requests_email" {}
variable "default_to" {}
variable "twilio_call_back_url" {}
variable "twilio_status_call_back_url" {}
variable "private_subnet_ids" {
    default = []
}
variable "dependency_id" {
    default = []
}

variable "anomaly_processor_port" {}
variable "asset_enricher_port" {}
variable "asset_manager_port" {}
variable "control_center_port" {}
variable "email_notification_service_port" {}
variable "escalation_manager_port" {}
variable "escalation_service_port" {}
variable "generic_data_source_port" {}
variable "kafka_port" {}
variable "loxone_data_source_port" {}
variable "mute_manager_port" {}
variable "mute_service_port" {}
variable "north_data_source_port" {}
variable "notification_permissions_manager_port" {}
variable "notifications_enricher_port" {}
variable "offline_sensor_manager_port" {}
variable "offline_sensor_monitor_port" {}
variable "permissions_manager_port" {}
variable "response_manager_port" {}
variable "sensor_manager_port" {}
variable "sigfox_data_source_port" {}
variable "site_enricher_port" {}
variable "site_manager_port" {}
variable "system_manager_port" {}
variable "telegram_inbound_service_port" {}
variable "telegram_notification_service_port" {}
variable "texecom_data_source_port" {}
variable "threshold_anomaly_detector_port" {}
variable "threshold_model_manager_port" {}
variable "rateofchange_model_manager_port" {}
variable "rateofchange_anomaly_detector_port" {}
variable "spike_model_manager_port" {}
variable "ttn_dc2_raw_port" {}
variable "ttn_transformer_port" {}
variable "user_enricher_port" {}
variable "user_manager_port" {}
variable "webway_data_source_port" {}
variable "zookeeper_port" {}
variable "ehs_port" {}
variable "api_gateway_port" {}


variable "port_8080" {}
variable "anomaly_processor_target_group_arn" {}
variable "api_gateway_target_group_arn" {}
variable "asset_enricher_target_group_arn" {}
variable "asset_manager_target_group_arn" {}
variable "control_center_target_group_arn" {}
variable "ehs_target_group_arn" {}
variable "email_notification_service_target_group_arn" {}
variable "escalation_manager_target_group_arn" {}
variable "escalation_service_target_group_arn" {}
variable "generic_data_source_target_group_arn" {}
variable "loxone_data_source_target_group_arn" {}
variable "mute_manager_target_group_arn" {}
variable "mute_service_target_group_arn" {}
variable "notification_permissions_manager_target_group_arn" {}
variable "notifications_enricher_target_group_arn" {}
variable "offline_sensor_manager_target_group_arn" {}
variable "offline_sensor_monitor_target_group_arn" {}
variable "permissions_manager_target_group_arn" {}
variable "response_manager_target_group_arn" {}
variable "sensor_manager_target_group_arn" {}
variable "sigfox_data_source_target_group_arn" {}
variable "site_enricher_target_group_arn" {}
variable "site_manager_target_group_arn" {}
variable "system_manager_target_group_arn" {}
variable "telegram_inbound_service_target_group_arn" {}
variable "telegram_notification_service_target_group_arn" {}
variable "threshold_anomaly_detector_target_group_arn" {}
variable "threshold_model_manager_target_group_arn" {}
variable "rateofchange_model_manager_target_group_arn" {}
variable "rateofchange_anomaly_detector_target_group_arn" {}
variable "spike_model_manager_target_group_arn" {}
variable "ttn_dc2_raw_target_group_arn" {}
variable "ttn_transformer_target_group_arn" {}
variable "user_enricher_target_group_arn" {}
variable "user_manager_target_group_arn" {}
variable "webway_data_source_target_group_arn" {}
variable "gwt_data_source_target_group_arn" {}