task_family: "ZOO5-EXBTOR"
task_role_arn: ''
network_mode: 'bridge'
security_groups:
- "sg-09805348000013bbc"
subnets:
- "subnet-03517fa49d9c62bc1"
- "subnet-00b92bd4da32652df"
- "subnet-0fbdad730c927946a"

# First container
c1_appname: zoo5
c1_memory: 1024
c1_soft_memory: 512
c1_load_balancers:
- c1targetGroupArn: "{{zookeeper_target_group_arn}}"
  c1containerName: "zoo5"
  c1loadBalancerName: >
    "ZOOKEEPER-INTERNAL-{{env}}"
  c1containerPort: >
    {{zookeeper_port}}
c1_ports:
- c1hostPort: >
    {{zookeeper_port}}
  c1containerPort: >
    {{zookeeper_port}}
  c1protocol: tcp
- c1hostPort: >
    {{zookeeper_port_1}}
  c1containerPort: >
    {{zookeeper_port_1}}
  c1protocol: tcp
- c1hostPort: >
    {{zookeeper_port_2}}
  c1containerPort: >
    {{zookeeper_port_2}}
  c1protocol: tcp
- c1hostPort: >
    {{zookeeper_port_3}}
  c1containerPort: >
    {{zookeeper_port_3}}
  c1protocol: tcp
c1_image: confluent/zookeeper
c1_essential: True
c1_privileged: False
#c1_environment_variables:
#   - c1name: HOSTNAME
#     c1value: "zoo1.weave.local"

c1_awslogs_group: "/aws/ecs/{{env}}"
# Our logs go to eu-west-1
c1_log_region: "eu-west-1"
c1_awslogs_stream_prefix: zookeeper/
c1_docker_labels: zookeeper
c1_docker_security_options: no-new-privileges

# Volume attachment

src_volume_name: "zk-data"
volume_src_path: "/kafka-data/zookeeper-exhibitor/"
mount_container_path: "/opt/zookeeper/local_configs/"
mount_readonly_bool: False


# Service Setup
cluster_name: "Kafka-cluster-{{env}}"
service_name: "zookeeper5-service"
count: "1"

# Stage to Prod it has to be rolling update
maximumPercent: 200
minimumHealthyPercent: 100
