
- include: playbooks/zookeeper.yml
  vars:
    ecs_action: delete
    env: "{{env}}"
    region: "{{region}}"
    kafka_zk_cluster_name: "{{kafka_zk_cluster_name}}"

- include: playbooks/kafka.yml
  vars:
    ecs_action: delete
    env: "{{env}}"
    region: "{{region}}"
    kafka_zk_cluster_name: "{{kafka_zk_cluster_name}}"

