task_family: "ZOO1-EXBTOR"
task_role_arn: ''
network_mode: 'bridge'
security_groups:
  - "{{kafka_sg_id}}"
subnets:
  - "{{private_subnet_0}}"
  - "{{private_subnet_1}}"
  - "{{private_subnet_2}}"

# First container
c1_appname: zoo1
c1_memory: 1024
c1_soft_memory: 512
c1_load_balancers:
  - c1targetGroupArn: "{{zookeeper_target_group_arn}}"
    c1containerName: "zoo1"
    c1loadBalancerName: >
      "ZOOKEEPER-INTERNAL-{{env}}"
    c1containerPort: >
      {{zookeeper_port}}
c1_ports:
  - c1hostPort: >
      {{zookeeper_port}}
    c1containerPort: >
      {{zookeeper_port}}
    c1protocol: tcp
  - c1hostPort: >
      {{zookeeper_port_1}}
    c1containerPort: >
      {{zookeeper_port_1}}
    c1protocol: tcp
  - c1hostPort: >
      {{zookeeper_port_2}}
    c1containerPort: >
      {{zookeeper_port_2}}
    c1protocol: tcp
  - c1hostPort: >
      {{zookeeper_port_3}}
    c1containerPort: >
      {{zookeeper_port_3}}
    c1protocol: tcp
c1_image: confluentinc/cp-zookeeper
c1_essential: True
c1_privileged: False
c1_environment_variables:
- c1name: ZOOKEEPER_CLIENT_PORT
  c1value: >
    "{{zookeeper_port}}"
- c1name: ZOOKEEPER_SERVER_ID
  c1value: >
    "1"

c1_awslogs_group: "/aws/ecs/{{env}}"
# Our logs go to eu-west-1
c1_log_region: "eu-west-1"
c1_awslogs_stream_prefix: zookeeper/
c1_docker_labels: zookeeper
c1_docker_security_options: no-new-privileges

# Volume attachment

src_volume_name: "zk-data"
volume_src_path: "/kafka-data/zookeeper/"
mount_container_path: "/var/lib/zookeeper/"
mount_readonly_bool: False


# Service Setup
cluster_name: "Kafka-cluster-{{env}}"
service_name: "zookeeper1-service"
count: "1"

# Stage to Prod it has to be rolling update
maximumPercent: 200
minimumHealthyPercent: 100
